### PR TITLE
Feature/demo network linkout

### PR DESCRIPTION
**Pull request by mikekucera**
**General information**

Associated issues: #245

**Checklist**

Author:

- [x] One or more reviewers have been assigned.
- [ ] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.
- [x] The associated GitHub issues are included (above).
- [x] Notes have been included (below).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.  Reviewers have two business days to review the pull request, after which the author may merge in the pull request unilaterally.

**Notes**

Christian and I discussed how to handle this. There's no obvious place to put a link in the network viewer. Adding a link to the header looks strange and doesn't work nicely with mobile layout. Adding an icon would probably not be noticed by users. I tried adding a link over the network area and Christian didn't even notice it.

So, we decided to show the upload dialog  when clicking the "view demo network" link on the home page. The dialog just has a sentence about where the network is from, and provides a link. The user just clicks the "Create Network" button to create the demo network.

This dialog page could be enhanced in the future with a selection of demo networks, or more links. We could also warn the user if they already have a demo network stored in their local storage.

This PR also fixes the bug where creating the demo network couldn't be cancelled.

Screenshot 2024-02-23 at 4 09 26 PM

### CODE REVIEW

**Comment by maxkfranz** [comment]
Looks great.

Minor style suggestions:

- Rounding the corners of the image would make it look better, where it's inline.
- The alignment on the PC logo is a bit weird.  Would making it smaller help?
- I didn't see the update on https://dev.enrichmentmap.org .  Does the link to the PC tutorial open in a new tab?

**Comment by mikekucera** [comment]
I'll make the changes and push it to dev so you can see it. 

It opens this URL in a new tab: https://www.pathwaycommons.org/guide/workflows/rna_seq_to_enrichment_map/process_data/
 
It goes straight to the first section of the RNA-Seq tutorial which just talks about the background and creating the input file. The next two sections talk about how to run GSEA and EM-desktop, which isn't relevant and might be confusing.

**Comment by maxkfranz** [comment]
The PC guide could also be updated to refer to enrichmentmap.org

**Review by maxkfranz — APPROVED** [review]

**Comment by mikekucera** [comment]
merged manually

**Pull request closed without merging**
