### PR TITLE
The bottom drawer is now expanded by default

### PR DESCRIPTION
**Pull request by chrtannus**
**General information**

Associated issues:  #208

**Checklist**

Author:

- [X] One or more reviewers have been assigned.
- [ ] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.
- [X] The associated GitHub issues are included (above).
- [X] Notes have been included (below).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.  Reviewers have two business days to review the pull request, after which the author may merge in the pull request unilaterally.

**Notes**
- The Pathway table is now shown by default.
- When creating a new network, it should fit the available network area.

### CODE REVIEW

**Comment by chrtannus** [comment]
@mikekucera:
I noticed that the newly created network doesn't fit the canvas area properly, but I can't figure out why.
The controller is calling  `this.cy.fit(DEFAULT_PADDING)` on `_setZoomMinMax()` after applying the layout, but if you click the "Fit Figure to Screen" button after creating a network or restoring it to its initial layout, it then zooms out a little bit more to fit it as expected.
Could you please help me find the problem here?

**Comment by mikekucera** [comment]
Its because the first time fit() is called before the compound nodes are added to the network.

**Comment by mikekucera** [comment]
I'll fix it and add a commit to this branch

**Comment by mikekucera** [comment]
Nevermind that didn't fix it, still working on it 😤

**Comment by mikekucera** [comment]
Ok I think I got it. 

The `fit()` function must be called after... 1) the compound nodes are created, 2) the style is applied, 3) the labels are ready. 

Currently `node.data('label')` is set in the `SearchControler.fetchAllPathwaysInNetwork()` function. So the extra width of the labels isn't taken into account when the network itself is done loading, because the labels aren't set until after the pathway list is fetched.

I propose we go back to the previous way of doing labels, using the memoized function in `network-style.js` that's currently commented out (but without the truncation). I would create a utility function for parsing the pathway name and share it between `network-style.js` and the `SearchController`

What do you think?

**Comment by chrtannus** [comment]
Ok, let's do that then. Thanks!

**Review by mikekucera — APPROVED** [review]

**Pull request merged**
