### PR TITLE
Feedback: Errors & UI warnings

### PR DESCRIPTION
**Pull request by maxkfranz**
**General information**

This is a PR for discussion re. error handling.  It is not currently to be considered for merging.

Associated issues: 

- #46 

**Checklist**

Author:

- [ ] One or more reviewers have been assigned.
- [ ] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.
- [ ] The associated GitHub issues are included (above).
- [ ] Notes have been included (below).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.  Reviewers have two business days to review the pull request, after which the author may merge in the pull request unilaterally.

**Notes**

(1) Goal:  Enable us to show clear feedback to users when there is a problem with their input data.
  - Approach:  Use [a number of error (exception) classes](https://github.com/cytoscape/enrichment-map-webapp/blob/2467b34de1b25b5c59d47ffc7764422aa1096e42/src/model/errors.js).
  - Approach:  The error classes should each contain enough information for the UI to show clear feedback.  The UI should determine how and what to display, and the error objects should just have context.
  - Example:  Joe has an invalid cell in his input spreadsheet.  The cell should have a number, but it doesn't.  There are several types of feedback Joe could be given, depending on the design:
    - (A) Joe sees just a text message, e.g. 'your file has incorrectly formatted numbers'.
    - (B) Joe gets a descriptive text message, e.g. 'your file has an incorrect number at cell C12'.
    - (C) Joe gets a descriptive text message and also a nice visual summary of the incorrect cells, like an abbreviated view of the spreadsheet with the incorrect cells in red.
  - Discussion:  What changes to the errors should we make?  We currently just have a rough draft, so we should consider the following:
    - What other error types should we consider?
    - What data (context) should go in each one?
    - Should we have something like a `ManyErrors` class that can reference multiple errors without losing the general exception context (e.g. as may be used to facilitate example C)?
    - Other considerations

(2) Goal:  Unify the way that errors are handled in the services and the UI to facilitate (1).
  - Approach:  The services should return JSON error objects that correspond to serialised JSON of applicable error classes.
  - Approach:  The base query error class has a static factory function that can be used to generate the correct subtype error object, allowing the services to just send JSON back (rather than error message strings). 

(3) Goal:  Balance the amount of information (e.g. number of errors) shown to users at once.
  - Discussion:  We'll need to decide what balance to strike:
    - Showing many simultaneous errors v.s. showing one at a time (or one type at a time)
    - Example files as feedback
    - Excel file as feedback
    - Considering the number of times a user would have to edit and re-upload

### CODE REVIEW

**Comment by maxkfranz** [comment]
- Use example file as instruction to the user.
- Allow spreadsheet file download to open in Excel
- PC example tutorial?
- Direct demo link for example -- nice to have
- GProfiler example -- I didn't rec. these genes

**Comment by mikekucera** [comment]
I propose we break this into 2 phases…

Phase 1
- Minimal amount of data validation on client.
    - Basically just check that the input file is TSV, CSV or Excel.
    - Check the expected columns exist.
        - Ranks -> gene name, rank
        - RNASEQ -> gene name, description (optional), then multiple columns of numeric values
- Handle 500 errors from services
    - Handle 500 server errors in a generic way, and log them. That way we have data on what types of errors are actually happening. Eventually we can move some of that error checking to the client and make it preemptive.
    - Handle empty network in a generic way. There are a few reasons why the network could be empty (users genes don’t exist in our database, enriched geneses don’t pass filters, etc…). Just tell the user that their data could not be used to create a network.
- Provide the user with example data files for rnaseq and preranked.
    - We already have a graphic that shows a small example of each format, is that good enough?
    - Use example data from PC tutorial if possible. Maybe even link to PC tutorial.

Phase 2
- Use information from logged errors in Phase 1 to make informed decisions on how the data should be validated on the client.
- Implement robust data validation on the client. Tell the user they have specific problems with specific cells etc…
    - Note: If the user has rnaseq data, and they choose to ignore some columns in the “class chooser” step, then we should ignore data format errors in those columns.
    - Remove ignored columns when passing data to server, just to save bandwidth.
- Allow the user to create the network even if there is a “reasonable” amount of data errors. Replace invalid values with zeros or something like that.

Notes…

Client
- It’s theoretically possible to do comprehensive data validation on the client before passing the data to the server. The issue is we don’t currently know exactly what types of errors can happen with real user data.

Express Server
- 500 Errors. The express endpoint basically just calls the services with the data from the client, then stores the results in mongo. There’s not much that can go wrong here apart from critical 500 errors.

Services
- 500 Errors, unexpected bugs…
    - Just give the user a generic error message?
    - Log the error and send an email. 
- Known errors
    - FGSEA service
        - Data format errors. FGSEA throws an error if one of the rank values is NA.
        - A significant number of the genes in the input don’t exist in our gene set database.
            - Note, we can still calculate ranks for these genes, they just don’t contribute to enriched pathways.
        - None of the genes in the input exist in our gene set database.
            - This could indicate a problem with gene identifiers.
            - This will result in an empty network.
            - No reason to pass results along to the EM service.
    - EM service
        - Very few or zero enriched gene sets pass the cutoffs. 
            - I’m not sure how likely this is to happen, because it depends on how FGSEA works. But it could theoretically happen.

**Comment by maxkfranz** [comment]
A phased approach is a good idea.  Here are some notes:

- What we have now might not be sufficient for tracking down errors in Phase 1, even with the current approach with Sentry (#66).
  - (A) We could validate that the errors bubble up to Node so that there is enough information.
    - Add more sample data, with errors that we already know about.
    -  Verify that the error info bubbles up from the services in the response bodies (HTTP 500) to Node and that the errors are tracked by Sentry.
    - Optional: Add Sentry support directly to the Java service.  This will give better error info, and it's easy for [Spring](https://docs.sentry.io/platforms/java/guides/spring/) and [Spring Boot](https://docs.sentry.io/platforms/java/guides/spring-boot/).
    - Optional: Add Sentry support directly to the R/FGSEA service.  This would be expensive.  R is not supported out of the box.
  - (B) We could upload the query files to Sentry so that they're associated with their errors and user sessions.
    - Even if Sentry doesn't contain useful error messages, bubbled up from the services, we would have enough information to reproduce errors.
    - We have limited space for files on Sentry (1 GB).  The input files could be compressed on the client before upload.  They're probably well compressible by gzip.  For now, compressing may not be a priority.
  - (A) and (B) are not mutually exclusive.  However, (B) is sufficient on its own for Phase 1. 
- Other outstanding action items for Phase 1:
  - Add a link on the query view to a sample file.
  - Add a link on the error view to a sample file.
  - Minimal approach for empty networks:  Just throw an error on the Node server (for now) for empty network results.  This will show our existing, generic user-facing error message.  This can be improved upon in later phases.

**Comment by maxkfranz** [comment]
Since this discussion is finished for now, I'm closing this to clean up the list of open PRs.

**Pull request closed without merging**
