### PR TITLE
Feature/data export

### PR DESCRIPTION
**Pull request by mikekucera**
**General information**

Associated issues: #148

**Checklist**

Author:

- [x] One or more reviewers have been assigned.
- [ ] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.
- [x] The associated GitHub issues are included (above).
- [x] Notes have been included (below).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.  Reviewers have two business days to review the pull request, after which the author may merge in the pull request unilaterally.

**Notes**

- Adds an option to the Share menu called "Export Enrichment Data"
- Selecting this option allows the user to download a zip file that contains:
   - TSV file of the raw FGSEA enrichment results
   - TSV file of the gene ranks
   - TSV file containing the gene sets (ie a GMT file)
- The TSV files are generated on the server side from data in mongo. 
- If the download takes too long a spinner will show up as a snack bar.
- The resulting zip file can be imported into EM-desktop

### CODE REVIEW

**Comment by maxkfranz** [comment]
Notes:

- The UI looks fine.
- In future, we may need something in a FAQ to let people know that you can use this in Cytoscape.  Or there could be a send entry, e.g. 'Download for Cytoscape', even if the data is the same.
- The rank file has an error for `GSE129943_rsem_counts_2016`.
- Maybe @chrtannus could comment on how this works when you import it into Cytoscape.

[GSE129943_rsem_counts_2016_enrichment.zip](https://github.com/cytoscape/enrichment-map-webapp/files/12162642/GSE129943_rsem_counts_2016_enrichment.zip)

**Comment by mikekucera** [comment]
I need to figure out why it couldn't generate a ranks file for that network. Can you provide me with the network ID? Did you run it locally or on the dev server?

**Comment by maxkfranz** [comment]
I got the result locally on your branch with the sample network.

**Comment by mikekucera** [comment]
Ok, should work now. I accidentally hard-coded the ID of the test network I was using :sweat_smile:

**Comment by maxkfranz** [comment]
> Ok, should work now. I accidentally hard-coded the ID of the test network I was using 😅

Great.  Much better than a real bug.

**Review by maxkfranz — APPROVED** [review]
I think we should merge this in to try it out on the dev instance

**Pull request merged**
