### PR TITLE
Feature/legend marker

### PR DESCRIPTION
**Pull request by mikekucera**
**General information**

Associated issues: #101, #95

**Checklist**

Author:

- [x] One or more reviewers have been assigned.
- [ ] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.
- [x] The associated GitHub issues are included (above).
- [x] Notes have been included (below).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.  Reviewers have two business days to review the pull request, after which the author may merge in the pull request unilaterally.

**Notes**

This PR does the following...
- Adds a marker to the legend that shows the NES of the currently selected node.
- The marker is not included when exporting the legend image.
- Note: The legend is a bit wider, and looks a bit empty when nothing is selected. Suggestions are welcome.

https://user-images.githubusercontent.com/5350528/230501683-4afb22db-f33a-4f3c-b8eb-317ece59e312.mov

### CODE REVIEW

**Comment by maxkfranz** [comment]
I had this sketch last week, but I didn’t have time to post it.  It’s without any explanation, but maybe there are some useful ideas for reducing the space taken:

[EM web legend compression sketch.pdf](https://github.com/cytoscape/enrichment-map-webapp/files/11191061/EM.web.legend.compression.sketch.pdf)

I can discuss this more, if needed, next week when I’m back.

**Comment by mikekucera** [comment]
That's much better. I like how it avoids the empty space to the left of the gradient when nothing is selected. I'll make the changes.

**Comment by mikekucera** [comment]
I redesigned the legend to look like the mockup. I moved the "collapse" button to the top of the legend, to make it look more symmetrical. The only word on the legend now is "Enrichment", a tooltip is used to explain that its NES and what NES stands for.


https://user-images.githubusercontent.com/5350528/231567322-123442b8-cfae-42ae-89ee-953fdc6ea539.mov

**Review by chrtannus — APPROVED** [review]

**Comment by maxkfranz** [comment]
A small style improvement:

Screenshot 2023-04-17 at 11 17 02


- Better cross-platform font stack that matches that of the app itself.
- No background colour on the selected score text.  With a grey background colour, it appears as though it has some meaning.  Is the grey the colour of the score?  Is something disabled because it's grey?  Without the background, there's less chance of a user erroneously interpreting meaning where there is none.

**Comment by maxkfranz** [comment]
The before picture:

Screenshot 2023-04-17 at 11 22 01

**Comment by maxkfranz** [comment]
Any objections to merging this in?

**Comment by mikekucera** [comment]
I have no objections :)

**Pull request merged**
