### PR TITLE
Feature/bubbles revised 2

### PR DESCRIPTION
**Pull request by mikekucera**
**General information**

Associated issues: #264 
Associated PR (this PR extends the previous PR): https://github.com/cytoscape/enrichment-map-webapp/pull/274

**Checklist**

Author:

- [x] One or more reviewers have been assigned.
- [ ] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.
- [x] The associated GitHub issues are included (above).
- [x] Notes have been included (below).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.  Reviewers have two business days to review the pull request, after which the author may merge in the pull request unilaterally.

**Notes**

This PR branches off from Max's PR here: https://github.com/cytoscape/enrichment-map-webapp/pull/274
This is a separate PR because it contains many changes that need to be discussed.

This PR does the following...
- Reverts some of the style changes from PR [#274](https://github.com/cytoscape/enrichment-map-webapp/pull/274)
  - The issues with label casing have been addressed by using the 'description' field, so the uppercasing is no longer needed.
  - Moved labels back to the center of the nodes. There was too much overlapping of labels with other nodes when they were moved to the top of the node.
- Reverts the behaviour where clicking away from a cluster collapses it.
  - We discussed this on a status call. There are a few issues with this behaviour
    - If the user wants to expand multiple clusters for exporting network images they won't be able to do that.
    - Clicking on the background is overloaded, it deselects nodes and collapses clusters, this makes it very hard to deselect the nodes in the cluster because you end up collapsing the cluster instead.
- New behaviour:
  - There is now a prominent Expand/Collapse button at the bottom of each cluster. Currently it shows up when hovering over the compound node (not the bubble).
  - The button is below all the nodes in the cluster, so it no longer overlaps the nodes in the cluster. It also has different colors. This makes it much more obvious.
  - The button actually says "Expand" or "Collapse", hopefully making its use more clear.
  - The *only* way to expand/collapse is to click the button. Clicking the compound node is only used to drag or select. Clicking the bubble does nothing. The intention is that this will be more clear since Expand/Collapse is now a very explicit gesture that requires clicking a button. None of the network gestures are overloaded.

- Issues:
  - Placing the button at the bottom-center of the clusters requires a change to cytoscape-layers extension. This PR currently pulls a modified version of cytoscape-layers from my personal NPM account. If we like these buttons we'll have to contribute the change back to cytoscape-layers.
  - The buttons look kind of basic, we can discuss how they should look.
  - Hovering doesn't work on mobile.
    - We can discuss strategies for mobile. For example the cluster closest to the center could have the button appear automatically.

Screenshot 2024-04-10 at 2 01 19 PM
Screenshot 2024-04-10 at 2 01 33 PM

### CODE REVIEW

**Comment by mikekucera** [comment]
It looks like the dev server doesn't like my custom build of cytoscape-layers. I have no idea how to fix the issue. To test this branch please check it out locally.

**Comment by mikekucera** [comment]
did you try running 'npm install' ?

**Comment by chrtannus** [comment]
Yes, but "npm i" did not fix it.

**Comment by mikekucera** [comment]
The issue is that in this branch EM-web and the bubble-clusters extension both depend on different versions of cytoscape-layers. I have a fairly recent version of node on my computer that seems to support this. I bet you and the dev server have older versions of node.

**Comment by mikekucera** [comment]
- Moved the button back to the center of the cluster.
  - This mitigates button placement issues with irregularly shaped clusters.
  - Removes need for custom patched cytoscape-layers extension.
- Button now automatically hides itself after a 3 second timeout.
  - Mitigates issue where button overlaps nodes under it. 

Screenshot 2024-04-11 at 12 48 54 PM
Screenshot 2024-04-11 at 12 49 08 PM

**Pull request merged**
