### PR TITLE
Feature/svg legend

### PR DESCRIPTION
**Pull request by mikekucera**
**General information**

Associated issues: #76

**Checklist**

Author:

- [x] One or more reviewers have been assigned.
- [x] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.
- [x] The associated GitHub issues are included (above).
- [x] Notes have been included (below).

Reviewers:

- [x] All automated checks are passing (green check next to latest commit).
- [x] At least one reviewer has signed off on the pull request.  Reviewers have two business days to review the pull request, after which the author may merge in the pull request unilaterally.

**Notes**

This PR makes the following changes...
- Replaces the cy.js based legend with a new legend using SVG.
- The legend can be exported as an SVG image file. (This action still has to be added to the share menu, but I did test it and it works).
- Moves the legend to the bottom-right. The legend overlays the network but is quite small so it shouldn't obscure too much. The legend can be collapsed down to a floating action button.

https://user-images.githubusercontent.com/5350528/228658676-015e26f3-92a3-445a-983f-ddc52869d7c2.mov

### CODE REVIEW

**Comment by maxkfranz** [comment]
This looks nice

I've only yet looked at the video so far, but here are some ideas that could improve some areas of the legend:

(1) The blue colour of the legend button, when it's collapsed, makes it look like it's not the legend anymore.  It just feels a bit weird.  It might be better if it's the same white colour as the legend's ordinary background.  Another idea would be to colour the button with the same gradient as the legend entry.  That gives a nice signifier that you'll get information about the colours when you click the collapsed button.

(2) It's useful to see the legend up front, when the user first gets to the results page.  Once you start interacting with the network, you probably would often collapse the legend.   You've seen it already and it takes up space more noticeably, for instance, when you zoom in.  A simple small improvement would be to automatically collapse the legend once you start interacting with the network, like if you zoom or pan.  You only need to see it once, after all.

(3) I'm not sure the 'Legend' title is strictly necessary.  Figures in papers don't often use a 'Legend' title.  That could save a little bit of space.

**Comment by mikekucera** [comment]
I don't want to use the same color as the nodes for the button color,
because I think it will make the button look like a node. I think it needs
to have a distinct color from the network. Either black like the
panels/toolbars for consistency, or white like the network background. I'll
try both and see how it looks.

I agree that it should be expanded initially.
I'm ok to remove the "Legend" title.

Thanks!

Mike.

**Comment by maxkfranz** [comment]
> I don't want to use the same color as the nodes for the button color,
> because I think it will make the button look like a node. 

Good point

**Comment by mikekucera** [comment]
Screenshots with a white button and background (actually its slightly grey). 

Screenshot 2023-03-30 at 1 39 44 PM

Screenshot 2023-03-30 at 1 39 27 PM

Here is with a dark color...

Screenshot 2023-03-30 at 1 52 54 PM

Screenshot 2023-03-30 at 1 53 01 PM


Here is without the "Legend" title...  the empty space looks kind of weird IMO. 

Screenshot 2023-03-30 at 1 39 20 PM

**Comment by chrtannus** [comment]
I like the light-grey background a little bit more (less intrusive on the network canvas, looks more like a legend and not another panel), but I prefer the dark round button (easier to find and differentiate from nodes).
Yes, it's weird without the "Legend" title.

**Comment by maxkfranz** [comment]
Either colour is an improvement over blue.

To clarify:  The title, 'Enrichment (NES)', should go up at the very top, beside the chevron, if we're looking to save space.  It doesn't need to be so far down if the NES is the only thing in the legend.

**Comment by mikekucera** [comment]
I'm going with the light-grey.

Moving "Expression (NES)" up next to the button requires the popup to be wider.

Screenshot 2023-03-30 at 4 32 18 PM

Another option is to move "Expression" to the top and keep "NES" on the color scale...

Screenshot 2023-03-30 at 4 29 56 PM

Personally I think it was fine with "Legend" at the top.

**Comment by chrtannus** [comment]
After thinking more about it: "Legend" tells the user what this little panel does. Without it, the user may wonder whether this may have another funcion: Is this another chart? Can I interact with it? Etc.

**Comment by maxkfranz** [comment]
Why don’t we go with the simplest thing for now, which is to go with Mike’s ‘Legend’ title?  What we have now is much better than what we had before.

I’ll log the further enhancement ideas (e.g. auto-collapse) so that we have them at hand.  If we run into issues re. legends or space in future, then we’ll already have some potential solutions to draw on.

**Review by maxkfranz — APPROVED** [review]
👍

**Pull request merged**
