### PR TITLE
Feature/report

### PR DESCRIPTION
**Pull request by mikekucera**
**General information**

Associated issues: #299 

**Checklist**

Author:

- [ ] One or more reviewers have been assigned.
- [ ] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.
- [ ] The associated GitHub issues are included (above).
- [ ] Notes have been included (below).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.  Reviewers have two business days to review the pull request, after which the author may merge in the pull request unilaterally.

**Notes**

- Adds endpoints on the server that return JSON info for a report.
- Adds a page on the client that shows a basic report.
- Security: 
  - A secret key must be provided as part of the URL.
  - This key is configured by an environment variable on the server.
  - The default value for the key is 'baderlab'
  - To access the report on a local instance go to `localhost:3000/report/baderlab`
  - On the prod server it will be `enrichmentmap.org/report/long-uuid-string`
- The UI is very basic for now, it just lists out all the non-demo networks on the server. For each network there is a link that opens the network.

Screenshot 2024-07-04 at 10 04 56 AM

### CODE REVIEW

**Comment by maxkfranz** [comment]
@mikekucera @chrtannus 

I'll put in a review tomorrow

**Comment by chrtannus** [comment]
It looks good to me!
Only one minor issue: when sorting by name, it should be case insensitive. In the example below, `brca_hd_tep_ranks` should be the first item:

ASC-sort-name

**Review by chrtannus — APPROVED** [review]

**Comment by mikekucera** [comment]
Good catch. Thanks.

**Comment by mikekucera** [comment]
I added a fix for the sorting issue to this branch. It also fixes the pathway table (#302).

**Comment by maxkfranz** [comment]
LGTM

**Pull request merged**
