### PR TITLE
Simple EM favicon

### PR DESCRIPTION
**Pull request by chrtannus**
**General information**

Associated issues: #64

**Checklist**

Author:

- [X] One or more reviewers have been assigned.
- [ ] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.
- [X] The associated GitHub issues are included (above).
- [X] Notes have been included (below).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.  Reviewers have two business days to review the pull request, after which the author may merge in the pull request unilaterally.

**Notes**

Adds a simple "EM" favicon as a 32x32 PNG file. It's just a small version of the logo.

To see the new favicon you may have to clear the browser cache (web content). On Safari for macOS, I had to delete the contents inside this folder: `~/Library/Safari/Favicon Cache`

  - _Chrome_:
    favicon-chrome-screenshot

 - _Firefox_:
    favicon-firefox-screenshot

  - _Safari_:
    favicon-safari-screenshot

### CODE REVIEW

**Comment by mikekucera** [comment]
Here's how it looks in dark mode. Looks pretty good to me.
What should we call the app? "RNA-seq to EM" is a placeholder right? If we're using the same icon as desktop should we just call the app "Enrichment Map"?

Screenshot 2023-04-04 at 5 04 26 PM

**Review by mikekucera — APPROVED** [review]

**Comment by maxkfranz** [comment]
I agree we should be consistent and call it ‘Enrichment Map’ for now

**Comment by chrtannus** [comment]
Right! But if we want to be really consistent, it should be "EnrichmentMap" (no space): https://apps.cytoscape.org/apps/enrichmentmap

**Comment by mikekucera** [comment]
> Right! But if we want to be really consistent, it should be "EnrichmentMap" (no space): https://apps.cytoscape.org/apps/enrichmentmap

Right

**Comment by chrtannus** [comment]
It now appears on Chrome/Android as well:

android-1

android-2

**Comment by chrtannus** [comment]
@maxkfranz & @mikekucera: Does it work on iOS too?

**Comment by chrtannus** [comment]
I agree, Max.
The `serve-favicon` library we are using is 5 years old and they haven't publish a new version.

So I'm now trying this [Real Favicon Generator](https://realfavicongenerator.net/) tool to generate the images, `site.webmanifest` and `browserconfig.xml` files, and HTML declarations, as suggested [here](https://fantinel.dev/fixing-favicons) and by others.

- That does solve the Android Home screen icon, but Safari now uses a monochrome icon for the tabs:
  safari-tab

- Safari's **Search** and **Favorites** look good, though:
  safari-search

  safari-favorites

**Comment by chrtannus** [comment]
I removed  `serve-favicon` and added more images in different sizes/versions and an .ico file (all declared in the HTML).

I  can now see the correct icon on the **Safari** tab again.
Can you please confirm it?

I also tested it on **Edge**/**Windows 11** and it looks good too:
favicon-edge-screenshot

Could you please test it on iOS?

**Pull request merged**
