### PR TITLE
Feature/landing page sections simple

### PR DESCRIPTION
**Pull request by chrtannus**
**General information**

Associated issues: #40, #169

**Checklist**

Author:

- [x] One or more reviewers have been assigned.
- [ ] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.
- [x] The associated GitHub issues are included (above).
- [x] Notes have been included (below).

Reviewers:

- [ ] All automated checks are passing (green check next to latest commit).
- [ ] At least one reviewer has signed off on the pull request.  Reviewers have two business days to review the pull request, after which the author may merge in the pull request unilaterally.

**Notes**

This is still a simple landing page, with only 3 sections:
- **Hero**
  - the header now has a menu with links to _FAQ_ and _About_
  - the menu is replaced with a hamburger icon/button that opens a top drawer/menu
- **FAQ**
- **About**: just the citation info + authors.

Please review the text and link outs as well.
Also, we still need a link or email address for the contact info (see link "reach out to us" in the FAQ section).

EMWeb-SimpleLandingPage

### CODE REVIEW

**Comment by mikekucera** [comment]
Maybe the first question should be something like... 

"What is an EnrichmentMap network?"

- EnrichmentMap performs gene-set enrichment analysis on a gene list then visualizes the results as a network.
Nodes represent gene-sets (pathways) and edges represent similarity (overlap) between the gene-sets.
The network is then structured so that highly redundant gene-sets are grouped together as clusters, dramatically improving the capability to navigate and interpret enrichment results.

Then the next question would be "How is the Enrichment analysis performed", then the rest of the questions. I just feel like we are still not telling the user what this app actually does. What is EnrichmentMap????

Other minor points...
- Can just say 'README file' instead of 'README.md file'. I don't think the extension on the README file matters and it makes it look more technical than in needs to be.
- In the answer for "Can I upload GSEA ... files?" it sounds like our app can't be used by a user that's already ran GSEA. But they could just start over using our app as long as they have the original gene list file. They don't necessarily have to download cytoscape. In fact FGSEA is so fast it would be easier for them to start over with EM-web then to go install cytoscape and EM-desktop.
- Under "what data does our app use" it should mention we only support Human.

**Comment by mikekucera** [comment]
Maybe a question like "How long does the enrichment analysis take?"... On average it takes 1-2 minutes to create the network from an uploaded file. Makes it sound very low-risk to try our app.

**Comment by chrtannus** [comment]
I made the suggested changes:

faq-questions-2

**Comment by mikekucera** [comment]
I like it. Gary and/or Max should review the text as well.

**Review by mikekucera — APPROVED** [review]

**Pull request merged**
